#! /bin/bash

function _usage() {
    echo "usage: $0 source_dir"
    exit 0
}

function _replace()
{
# this is generated by svn header change log
# cat svn-log | grep "A " | awk '{print $2}'| sed 's/\//\\\//g' | awk '{print "sed -i \"s/"$1"pp/"$1"/g\""" \$1"}'

sed -i "s/crypto\/random\/pseudo_random.hpp/crypto\/random\/pseudo_random.h/g" $1
sed -i "s/crypto\/random\/true_random.hpp/crypto\/random\/true_random.h/g" $1
sed -i "s/crypto\/hash\/sha1.hpp/crypto\/hash\/sha1.h/g" $1
sed -i "s/crypto\/hash\/string_hashes.hpp/crypto\/hash\/string_hashes.h/g" $1
sed -i "s/crypto\/hash\/crc.hpp/crypto\/hash\/crc.h/g" $1
sed -i "s/crypto\/hash\/md4.hpp/crypto\/hash\/md4.h/g" $1
sed -i "s/crypto\/hash\/md5.hpp/crypto\/hash\/md5.h/g" $1
sed -i "s/crypto\/hash\/fnv.hpp/crypto\/hash\/fnv.h/g" $1
sed -i "s/crypto\/hash\/consistent_hash\/consistent_hash.hpp/crypto\/hash\/consistent_hash\/consistent_hash.h/g" $1
sed -i "s/crypto\/hash\/city.hpp/crypto\/hash\/city.h/g" $1
sed -i "s/crypto\/hash\/murmur.hpp/crypto\/hash\/murmur.h/g" $1
sed -i "s/crypto\/hash\/fingerprint.hpp/crypto\/hash\/fingerprint.h/g" $1
sed -i "s/crypto\/credential\/verifier.hpp/crypto\/credential\/verifier.h/g" $1
sed -i "s/crypto\/credential\/generator.hpp/crypto\/credential\/generator.h/g" $1
sed -i "s/text\/wildcard.hpp/text\/wildcard.h/g" $1
sed -i "s/text\/xsv_parser.hpp/text\/xsv_parser.h/g" $1
sed -i "s/text\/regex\/regex_internal.hpp/text\/regex\/regex_internal.h/g" $1
sed -i "s/text\/regex\/regex.hpp/text\/regex\/regex.h/g" $1
sed -i "s/text\/regex\/regex_scanner.hpp/text\/regex\/regex_scanner.h/g" $1
sed -i "s/text\/regex\/value_parser.hpp/text\/regex\/value_parser.h/g" $1
sed -i "s/text\/template\/clear_silver.hpp/text\/template\/clear_silver.h/g" $1
sed -i "s/text\/template\/hdf.hpp/text\/template\/hdf.h/g" $1
sed -i "s/text\/csv_parser.hpp/text\/csv_parser.h/g" $1
sed -i "s/text\/tsv_parser.hpp/text\/tsv_parser.h/g" $1
sed -i "s/system\/timer\/timer_manager.hpp/system\/timer\/timer_manager.h/g" $1
sed -i "s/system\/net\/socket_address.hpp/system\/net\/socket_address.h/g" $1
sed -i "s/system\/net\/get_ip.hpp/system\/net\/get_ip.h/g" $1
sed -i "s/system\/net\/ip_address.hpp/system\/net\/ip_address.h/g" $1
sed -i "s/system\/net\/domain_resolver.hpp/system\/net\/domain_resolver.h/g" $1
sed -i "s/system\/net\/socket.hpp/system\/net\/socket.h/g" $1
sed -i "s/system\/debug\/hex_dump.hpp/system\/debug\/hex_dump.h/g" $1
sed -i "s/system\/debug\/print_trace.hpp/system\/debug\/print_trace.h/g" $1
sed -i "s/system\/cpu\/rdtsc.hpp/system\/cpu\/rdtsc.h/g" $1
sed -i "s/system\/concurrency\/condition_variable.hpp/system\/concurrency\/condition_variable.h/g" $1
sed -i "s/system\/concurrency\/blocking_queue.hpp/system\/concurrency\/blocking_queue.h/g" $1
sed -i "s/system\/concurrency\/named_pipe.hpp/system\/concurrency\/named_pipe.h/g" $1
sed -i "s/system\/concurrency\/named_pipe_windows.hpp/system\/concurrency\/named_pipe_windows.h/g" $1
sed -i "s/system\/concurrency\/scoped_locker.hpp/system\/concurrency\/scoped_locker.h/g" $1
sed -i "s/system\/concurrency\/sync_event.hpp/system\/concurrency\/sync_event.h/g" $1
sed -i "s/system\/concurrency\/cond.hpp/system\/concurrency\/cond.h/g" $1
sed -i "s/system\/concurrency\/this_thread.hpp/system\/concurrency\/this_thread.h/g" $1
sed -i "s/system\/concurrency\/base_thread.hpp/system\/concurrency\/base_thread.h/g" $1
sed -i "s/system\/concurrency\/named_pipe_unix.hpp/system\/concurrency\/named_pipe_unix.h/g" $1
sed -i "s/system\/concurrency\/fixed_thread_pool.hpp/system\/concurrency\/fixed_thread_pool.h/g" $1
sed -i "s/system\/concurrency\/thread_local.hpp/system\/concurrency\/thread_local.h/g" $1
sed -i "s/system\/concurrency\/event.hpp/system\/concurrency\/event.h/g" $1
sed -i "s/system\/concurrency\/once.hpp/system\/concurrency\/once.h/g" $1
sed -i "s/system\/concurrency\/rwspinlock.hpp/system\/concurrency\/rwspinlock.h/g" $1
sed -i "s/system\/concurrency\/rwlock.hpp/system\/concurrency\/rwlock.h/g" $1
sed -i "s/system\/concurrency\/mutex.hpp/system\/concurrency\/mutex.h/g" $1
sed -i "s/system\/concurrency\/lite_rwlock.hpp/system\/concurrency\/lite_rwlock.h/g" $1
sed -i "s/system\/concurrency\/spinlock.hpp/system\/concurrency\/spinlock.h/g" $1
sed -i "s/system\/concurrency\/semaphore.hpp/system\/concurrency\/semaphore.h/g" $1
sed -i "s/system\/concurrency\/rwlock_base.hpp/system\/concurrency\/rwlock_base.h/g" $1
sed -i "s/system\/concurrency\/thread_types.hpp/system\/concurrency\/thread_types.h/g" $1
sed -i "s/system\/concurrency\/thread_pool.hpp/system\/concurrency\/thread_pool.h/g" $1
sed -i "s/system\/concurrency\/thread.hpp/system\/concurrency\/thread.h/g" $1
sed -i "s/system\/concurrency\/sequence_lock.hpp/system\/concurrency\/sequence_lock.h/g" $1
sed -i "s/system\/concurrency\/thread_group.hpp/system\/concurrency\/thread_group.h/g" $1
sed -i "s/system\/time\/datetime.hpp/system\/time\/datetime.h/g" $1
sed -i "s/system\/time\/timestamp.hpp/system\/time\/timestamp.h/g" $1
sed -i "s/system\/time\/stopwatch.hpp/system\/time\/stopwatch.h/g" $1
sed -i "s/system\/time\/time_utils.hpp/system\/time\/time_utils.h/g" $1
sed -i "s/system\/time\/posix_time.hpp/system\/time\/posix_time.h/g" $1
sed -i "s/system\/dynamic_library.hpp/system\/dynamic_library.h/g" $1
sed -i "s/system\/console\/text_color_switcher.hpp/system\/console\/text_color_switcher.h/g" $1
sed -i "s/system\/signal.hpp/system\/signal.h/g" $1
sed -i "s/system\/process.hpp/system\/process.h/g" $1
sed -i "s/system\/uuid\/uuid.hpp/system\/uuid\/uuid.h/g" $1
sed -i "s/system\/io\/path.hpp/system\/io\/path.h/g" $1
sed -i "s/system\/io\/file_utility.hpp/system\/io\/file_utility.h/g" $1
sed -i "s/system\/io\/directory.hpp/system\/io\/directory.h/g" $1
sed -i "s/system\/io\/file.hpp/system\/io\/file.h/g" $1
sed -i "s/system\/io\/textfile.hpp/system\/io\/textfile.h/g" $1
sed -i "s/system\/memory\/protobuf_message_pool.hpp/system\/memory\/protobuf_message_pool.h/g" $1
sed -i "s/system\/memory\/unaligned.hpp/system\/memory\/unaligned.h/g" $1
sed -i "s/system\/memory\/mempool.hpp/system\/memory\/mempool.h/g" $1
sed -i "s/system\/memory\/free_list.hpp/system\/memory\/free_list.h/g" $1
sed -i "s/system\/memory\/unaligned\/align_insensitive.hpp/system\/memory\/unaligned\/align_insensitive.h/g" $1
sed -i "s/system\/memory\/unaligned\/check_direct_include.hpp/system\/memory\/unaligned\/check_direct_include.h/g" $1
sed -i "s/system\/memory\/unaligned\/gcc.hpp/system\/memory\/unaligned\/gcc.h/g" $1
sed -i "s/system\/memory\/unaligned\/generic.hpp/system\/memory\/unaligned\/generic.h/g" $1
sed -i "s/system\/memory\/unaligned\/msc.hpp/system\/memory\/unaligned\/msc.h/g" $1
sed -i "s/system\/memory\/barrier.hpp/system\/memory\/barrier.h/g" $1
sed -i "s/system\/ipc\/message_queue.hpp/system\/ipc\/message_queue.h/g" $1
sed -i "s/system\/check_error.hpp/system\/check_error.h/g" $1
sed -i "s/net\/uri\/uri.hpp/net\/uri\/uri.h/g" $1
sed -i "s/net\/uri\/cgi_params.hpp/net\/uri\/cgi_params.h/g" $1
sed -i "s/net\/tokamak\/eventfd.hpp/net\/tokamak\/eventfd.h/g" $1
sed -i "s/net\/tokamak\/async_secure_socket.hpp/net\/tokamak\/async_secure_socket.h/g" $1
sed -i "s/net\/tokamak\/socket_status.hpp/net\/tokamak\/socket_status.h/g" $1
sed -i "s/net\/tokamak\/io_event_handler.hpp/net\/tokamak\/io_event_handler.h/g" $1
sed -i "s/net\/tokamak\/example\/async_crawler.hpp/net\/tokamak\/example\/async_crawler.h/g" $1
sed -i "s/net\/tokamak\/signal_handler.hpp/net\/tokamak\/signal_handler.h/g" $1
sed -i "s/net\/tokamak\/timer_handler.hpp/net\/tokamak\/timer_handler.h/g" $1
sed -i "s/net\/tokamak\/interrupter.hpp/net\/tokamak\/interrupter.h/g" $1
sed -i "s/net\/tokamak\/async_socket.hpp/net\/tokamak\/async_socket.h/g" $1
sed -i "s/net\/tokamak\/tokamak.hpp/net\/tokamak\/tokamak.h/g" $1
sed -i "s/net\/tokamak\/aio_service.hpp/net\/tokamak\/aio_service.h/g" $1
sed -i "s/net\/tokamak\/proactor.hpp/net\/tokamak\/proactor.h/g" $1
sed -i "s/net\/tokamak\/statistics.hpp/net\/tokamak\/statistics.h/g" $1
sed -i "s/net\/tokamak\/socket_context.hpp/net\/tokamak\/socket_context.h/g" $1
sed -i "s/net\/tokamak\/reactor.hpp/net\/tokamak\/reactor.h/g" $1
sed -i "s/net\/tokamak\/command.hpp/net\/tokamak\/command.h/g" $1
sed -i "s/algorithm\/integer.hpp/algorithm\/integer.h/g" $1
sed -i "s/algorithm\/string.hpp/algorithm\/string.h/g" $1
sed -i "s/encoding\/percent.hpp/encoding\/percent.h/g" $1
sed -i "s/encoding\/ascii.hpp/encoding\/ascii.h/g" $1
sed -i "s/encoding\/json_to_pb.hpp/encoding\/json_to_pb.h/g" $1
sed -i "s/encoding\/pb_to_json.hpp/encoding\/pb_to_json.h/g" $1
sed -i "s/encoding\/charset_converter.hpp/encoding\/charset_converter.h/g" $1
sed -i "s/encoding\/variant_integer.hpp/encoding\/variant_integer.h/g" $1
sed -i "s/encoding\/hex.hpp/encoding\/hex.h/g" $1
sed -i "s/encoding\/base64.hpp/encoding\/base64.h/g" $1
sed -i "s/encoding\/gb.hpp/encoding\/gb.h/g" $1
sed -i "s/collection\/prefix_map.hpp/collection\/prefix_map.h/g" $1
sed -i "s/collection\/memory_cache.hpp/collection\/memory_cache.h/g" $1
sed -i "s/collection\/bitmap.hpp/collection\/bitmap.h/g" $1
sed -i "s/collection\/bloom_filter.hpp/collection\/bloom_filter.h/g" $1
sed -i "s/database\/sqlite3\/sqlite3.hpp/database\/sqlite3\/sqlite3.h/g" $1
sed -i "s/compression\/block\/compression_test_helper.hpp/compression\/block\/compression_test_helper.h/g" $1
sed -i "s/netframe\/epoll_event_poller.hpp/netframe\/epoll_event_poller.h/g" $1
sed -i "s/netframe\/eventfd_interrupter.hpp/netframe\/eventfd_interrupter.h/g" $1
sed -i "s/netframe\/event_poller.hpp/netframe\/event_poller.h/g" $1
sed -i "s/netframe\/pipe_interrupter.hpp/netframe\/pipe_interrupter.h/g" $1
sed -i "s/netframe\/netframe.hpp/netframe\/netframe.h/g" $1
sed -i "s/netframe\/packet.hpp/netframe\/packet.h/g" $1
sed -i "s/netframe\/stream_socket_context.hpp/netframe\/stream_socket_context.h/g" $1
sed -i "s/netframe\/work_thread.hpp/netframe\/work_thread.h/g" $1
sed -i "s/netframe\/command_event.hpp/netframe\/command_event.h/g" $1
sed -i "s/netframe\/command_queue.hpp/netframe\/command_queue.h/g" $1
sed -i "s/netframe\/interrupter.hpp/netframe\/interrupter.h/g" $1
sed -i "s/netframe\/socket_handler.hpp/netframe\/socket_handler.h/g" $1
sed -i "s/netframe\/socket_context.hpp/netframe\/socket_context.h/g" $1
sed -i "s/netframe\/datagram_socket_context.hpp/netframe\/datagram_socket_context.h/g" $1
sed -i "s/netframe\/wsa_event_poller.hpp/netframe\/wsa_event_poller.h/g" $1
sed -i "s/netframe\/listen_socket_context.hpp/netframe\/listen_socket_context.h/g" $1
sed -i "s/config\/xml\/xml_configer.hpp/config\/xml\/xml_configer.h/g" $1
sed -i "s/config\/cflags.hpp/config\/cflags.h/g" $1
sed -i "s/base\/byte_order.hpp/base\/byte_order.h/g" $1
sed -i "s/base\/cxx_demangle.hpp/base\/cxx_demangle.h/g" $1
sed -i "s/base\/int_cast.hpp/base\/int_cast.h/g" $1
sed -i "s/base\/barrier_closure.hpp/base\/barrier_closure.h/g" $1
sed -i "s/base\/function.hpp/base\/function.h/g" $1
sed -i "s/base\/any.hpp/base\/any.h/g" $1
sed -i "s/base\/unique_ptr.hpp/base\/unique_ptr.h/g" $1
sed -i "s/base\/ref_counted.hpp/base\/ref_counted.h/g" $1
sed -i "s/base\/object_pool.hpp/base\/object_pool.h/g" $1
sed -i "s/base\/any_ptr.hpp/base\/any_ptr.h/g" $1
sed -i "s/base\/string\/concat.hpp/base\/string\/concat.h/g" $1
sed -i "s/base\/string\/string_piece.hpp/base\/string\/string_piece.h/g" $1
sed -i "s/base\/string\/string_algorithm.hpp/base\/string\/string_algorithm.h/g" $1
sed -i "s/base\/string\/string_number.hpp/base\/string\/string_number.h/g" $1
sed -i "s/base\/string\/algorithm.hpp/base\/string\/algorithm.h/g" $1
sed -i "s/base\/string\/compare.hpp/base\/string\/compare.h/g" $1
sed -i "s/base\/string\/byte_set.hpp/base\/string\/byte_set.h/g" $1
sed -i "s/base\/string\/format.hpp/base\/string\/format.h/g" $1
sed -i "s/base\/global_initialize.hpp/base\/global_initialize.h/g" $1
sed -i "s/base\/strict_bool.hpp/base\/strict_bool.h/g" $1
sed -i "s/base\/stdext\/iterator.hpp/base\/stdext\/iterator.h/g" $1
sed -i "s/base\/stdext\/shared_ptr.hpp/base\/stdext\/shared_ptr.h/g" $1
sed -i "s/base\/stdext\/hash_set.hpp/base\/stdext\/hash_set.h/g" $1
sed -i "s/base\/stdext\/vector_map.hpp/base\/stdext\/vector_map.h/g" $1
sed -i "s/base\/stdext\/deque_map.hpp/base\/stdext\/deque_map.h/g" $1
sed -i "s/base\/stdext\/string.hpp/base\/stdext\/string.h/g" $1
sed -i "s/base\/stdext\/pointee_compare.hpp/base\/stdext\/pointee_compare.h/g" $1
sed -i "s/base\/stdext\/associated_array.hpp/base\/stdext\/associated_array.h/g" $1
sed -i "s/base\/stdext\/vector_set.hpp/base\/stdext\/vector_set.h/g" $1
sed -i "s/base\/stdext\/array.hpp/base\/stdext\/array.h/g" $1
sed -i "s/base\/stdext\/deque_set.hpp/base\/stdext\/deque_set.h/g" $1
sed -i "s/base\/stdext\/algorithm.hpp/base\/stdext\/algorithm.h/g" $1
sed -i "s/base\/stdext\/unique_ptr.hpp/base\/stdext\/unique_ptr.h/g" $1
sed -i "s/base\/stdext\/vector.hpp/base\/stdext\/vector.h/g" $1
sed -i "s/base\/stdext\/hash_map.hpp/base\/stdext\/hash_map.h/g" $1
sed -i "s/base\/stdext\/intrusive_list.hpp/base\/stdext\/intrusive_list.h/g" $1
sed -i "s/base\/stdext\/hash_function.hpp/base\/stdext\/hash_function.h/g" $1
sed -i "s/base\/module.hpp/base\/module.h/g" $1
sed -i "s/base\/binary_version.hpp/base\/binary_version.h/g" $1
sed -i "s/base\/function\/param_annotation.hpp/base\/function\/param_annotation.h/g" $1
sed -i "s/base\/function\/invoker_storage_base.hpp/base\/function\/invoker_storage_base.h/g" $1
sed -i "s/base\/function\/param_check.hpp/base\/function\/param_check.h/g" $1
sed -i "s/base\/function\/invoker_storage.hpp/base\/function\/invoker_storage.h/g" $1
sed -i "s/base\/function\/function_traits.hpp/base\/function\/function_traits.h/g" $1
sed -i "s/base\/function\/bind.hpp/base\/function\/bind.h/g" $1
sed -i "s/base\/function\/function_base.hpp/base\/function\/function_base.h/g" $1
sed -i "s/base\/function\/function.hpp/base\/function\/function.h/g" $1
sed -i "s/base\/function\/param_traits.hpp/base\/function\/param_traits.h/g" $1
sed -i "s/base\/cflags.hpp/base\/cflags.h/g" $1
sed -i "s/base\/serialize\/stream.hpp/base\/serialize\/stream.h/g" $1
sed -i "s/base\/serialize\/xml_codec.hpp/base\/serialize\/xml_codec.h/g" $1
sed -i "s/base\/serialize\/stl.hpp/base\/serialize\/stl.h/g" $1
sed -i "s/base\/serialize\/json_codec.hpp/base\/serialize\/json_codec.h/g" $1
sed -i "s/base\/serialize\/base.hpp/base\/serialize\/base.h/g" $1
sed -i "s/base\/serialize\/binary_codec.hpp/base\/serialize\/binary_codec.h/g" $1
sed -i "s/base\/serialize\/type.hpp/base\/serialize\/type.h/g" $1
sed -i "s/base\/serialize\/serialize.hpp/base\/serialize\/serialize.h/g" $1
sed -i "s/base\/timed_stats.hpp/base\/timed_stats.h/g" $1
sed -i "s/base\/platform_features.hpp/base\/platform_features.h/g" $1
sed -i "s/base\/uint32_divisor.hpp/base\/uint32_divisor.h/g" $1
sed -i "s/base\/type_cast.hpp/base\/type_cast.h/g" $1
sed -i "s/base\/static_resource.hpp/base\/static_resource.h/g" $1
sed -i "s/base\/module\/dependency_map.hpp/base\/module\/dependency_map.h/g" $1
sed -i "s/base\/module\/module_a.hpp/base\/module\/module_a.h/g" $1
sed -i "s/base\/module\/module_b.hpp/base\/module\/module_b.h/g" $1
sed -i "s/base\/scoped_refptr.hpp/base\/scoped_refptr.h/g" $1
sed -i "s/base\/uncopyable.hpp/base\/uncopyable.h/g" $1
sed -i "s/base\/singleton.hpp/base\/singleton.h/g" $1
sed -i "s/base\/type_traits.hpp/base\/type_traits.h/g" $1
sed -i "s/base\/static_assert.hpp/base\/static_assert.h/g" $1
sed -i "s/base\/bit_mask_enum.hpp/base\/bit_mask_enum.h/g" $1
sed -i "s/web\/url_util.hpp/web\/url_util.h/g" $1
sed -i "s/web\/uri.hpp/web\/uri.h/g" $1
sed -i "s/web\/url.hpp/web\/url.h/g" $1
sed -i "s/web\/docid_calc.hpp/web\/docid_calc.h/g" $1
sed -i "s/web\/domain.hpp/web\/domain.h/g" $1
sed -i "s/web\/hash_value.hpp/web\/hash_value.h/g" $1
sed -i "s/common\/system\/concurrency\/atomic\/atomic.hpp/common\/system\/concurrency\/atomic\/atomic.h/g" $1
}

if [ $# != 1 ]; then
    _usage
fi

dir=$1

find $dir -type f | grep -v ".svn" | egrep "\.cpp|\.cc|\.h|\.i" | while read file
do
    _replace $file
done

echo "header replace done"
