# This file is automatically generated
#!/bin/bash
#
# Copyright (c) 2012, Tencent Inc.
#
# Author      : Michaelpeng <michaelpeng@tencent.com>
# Date        : Mar 20, 2012
#
# Description : This script is used to host the list of ip

ip[0]=10.6.222.17
port[0]=13632
ssh_port[0]=36000
user[0]=distcc
passwd[0]=distcc
install_dir[0]=/home/distcc

ip[1]=10.6.222.18
port[1]=13632
ssh_port[1]=36000
user[1]=distcc
passwd[1]=distcc
install_dir[1]=/home/distcc

