# This file is automatically generated
#!/bin/bash
#
# Copyright (c) 2012, Tencent Inc.
#
# Author      : Michaelpeng <michaelpeng@tencent.com>
# Date        : Mar 20, 2012
#
# Description : This script is used to host the list of ip

ip[0]=10.6.222.17
port[0]=13632
ssh_port[0]=36000
user[0]=distcc
passwd[0]=distcc
install_dir[0]=/home/distcc

ip[1]=10.6.222.18
port[1]=13632
ssh_port[1]=36000
user[1]=distcc
passwd[1]=distcc
install_dir[1]=/home/distcc

ip[2]=10.6.222.19
port[2]=13632
ssh_port[2]=36000
user[2]=distcc
passwd[2]=distcc
install_dir[2]=/home/distcc

ip[3]=10.6.222.20
port[3]=13632
ssh_port[3]=36000
user[3]=distcc
passwd[3]=distcc
install_dir[3]=/home/distcc

ip[4]=10.6.222.21
port[4]=13632
ssh_port[4]=36000
user[4]=distcc
passwd[4]=distcc
install_dir[4]=/home/distcc

ip[5]=10.6.222.22
port[5]=13632
ssh_port[5]=36000
user[5]=distcc
passwd[5]=distcc
install_dir[5]=/home/distcc

ip[6]=10.6.222.23
port[6]=13632
ssh_port[6]=36000
user[6]=distcc
passwd[6]=distcc
install_dir[6]=/home/distcc

ip[7]=10.6.222.24
port[7]=13632
ssh_port[7]=36000
user[7]=distcc
passwd[7]=distcc
install_dir[7]=/home/distcc

ip[8]=10.6.222.25
port[8]=13632
ssh_port[8]=36000
user[8]=distcc
passwd[8]=distcc
install_dir[8]=/home/distcc

ip[9]=10.6.222.52
port[9]=13632
ssh_port[9]=36000
user[9]=distcc
passwd[9]=distcc
install_dir[9]=/home/distcc

ip[10]=10.6.222.53
port[10]=13632
ssh_port[10]=36000
user[10]=distcc
passwd[10]=distcc
install_dir[10]=/home/distcc

ip[11]=10.6.222.56
port[11]=13632
ssh_port[11]=36000
user[11]=distcc
passwd[11]=distcc
install_dir[11]=/home/distcc

ip[12]=10.6.222.57
port[12]=13632
ssh_port[12]=36000
user[12]=distcc
passwd[12]=distcc
install_dir[12]=/home/distcc

ip[13]=10.6.222.60
port[13]=13632
ssh_port[13]=36000
user[13]=distcc
passwd[13]=distcc
install_dir[13]=/home/distcc

ip[14]=10.6.222.61
port[14]=13632
ssh_port[14]=36000
user[14]=distcc
passwd[14]=distcc
install_dir[14]=/home/distcc

ip[15]=10.6.222.62
port[15]=13632
ssh_port[15]=36000
user[15]=distcc
passwd[15]=distcc
install_dir[15]=/home/distcc

ip[16]=10.6.222.63
port[16]=13632
ssh_port[16]=36000
user[16]=distcc
passwd[16]=distcc
install_dir[16]=/home/distcc

ip[17]=10.6.222.64
port[17]=13632
ssh_port[17]=36000
user[17]=distcc
passwd[17]=distcc
install_dir[17]=/home/distcc

ip[18]=10.6.222.65
port[18]=13632
ssh_port[18]=36000
user[18]=distcc
passwd[18]=distcc
install_dir[18]=/home/distcc

ip[19]=10.6.222.66
port[19]=13632
ssh_port[19]=36000
user[19]=distcc
passwd[19]=distcc
install_dir[19]=/home/distcc

ip[20]=10.6.222.67
port[20]=13632
ssh_port[20]=36000
user[20]=distcc
passwd[20]=distcc
install_dir[20]=/home/distcc

ip[21]=10.6.222.107
port[21]=13632
ssh_port[21]=36000
user[21]=distcc
passwd[21]=distcc
install_dir[21]=/home/distcc

ip[22]=10.6.222.108
port[22]=13632
ssh_port[22]=36000
user[22]=distcc
passwd[22]=distcc
install_dir[22]=/home/distcc

ip[23]=10.6.222.109
port[23]=13632
ssh_port[23]=36000
user[23]=distcc
passwd[23]=distcc
install_dir[23]=/home/distcc

ip[24]=10.6.222.110
port[24]=13632
ssh_port[24]=36000
user[24]=distcc
passwd[24]=distcc
install_dir[24]=/home/distcc

ip[25]=10.6.222.111
port[25]=13632
ssh_port[25]=36000
user[25]=distcc
passwd[25]=distcc
install_dir[25]=/home/distcc

ip[26]=10.6.222.112
port[26]=13632
ssh_port[26]=36000
user[26]=distcc
passwd[26]=distcc
install_dir[26]=/home/distcc

ip[27]=10.6.222.113
port[27]=13632
ssh_port[27]=36000
user[27]=distcc
passwd[27]=distcc
install_dir[27]=/home/distcc

ip[28]=10.6.222.114
port[28]=13632
ssh_port[28]=36000
user[28]=distcc
passwd[28]=distcc
install_dir[28]=/home/distcc

ip[29]=10.6.222.115
port[29]=13632
ssh_port[29]=36000
user[29]=distcc
passwd[29]=distcc
install_dir[29]=/home/distcc

ip[30]=10.6.222.116
port[30]=13632
ssh_port[30]=36000
user[30]=distcc
passwd[30]=distcc
install_dir[30]=/home/distcc

ip[31]=10.6.222.117
port[31]=13632
ssh_port[31]=36000
user[31]=distcc
passwd[31]=distcc
install_dir[31]=/home/distcc

ip[32]=10.6.222.118
port[32]=13632
ssh_port[32]=36000
user[32]=distcc
passwd[32]=distcc
install_dir[32]=/home/distcc

ip[33]=10.6.222.119
port[33]=13632
ssh_port[33]=36000
user[33]=distcc
passwd[33]=distcc
install_dir[33]=/home/distcc

ip[34]=10.6.222.120
port[34]=13632
ssh_port[34]=36000
user[34]=distcc
passwd[34]=distcc
install_dir[34]=/home/distcc

ip[35]=10.6.222.121
port[35]=13632
ssh_port[35]=36000
user[35]=distcc
passwd[35]=distcc
install_dir[35]=/home/distcc

ip[36]=10.6.222.122
port[36]=13632
ssh_port[36]=36000
user[36]=distcc
passwd[36]=distcc
install_dir[36]=/home/distcc

ip[37]=10.6.222.123
port[37]=13632
ssh_port[37]=36000
user[37]=distcc
passwd[37]=distcc
install_dir[37]=/home/distcc

ip[38]=10.6.222.124
port[38]=13632
ssh_port[38]=36000
user[38]=distcc
passwd[38]=distcc
install_dir[38]=/home/distcc

ip[39]=10.6.222.125
port[39]=13632
ssh_port[39]=36000
user[39]=distcc
passwd[39]=distcc
install_dir[39]=/home/distcc

ip[40]=10.6.222.126
port[40]=13632
ssh_port[40]=36000
user[40]=distcc
passwd[40]=distcc
install_dir[40]=/home/distcc

ip[41]=10.6.222.127
port[41]=13632
ssh_port[41]=36000
user[41]=distcc
passwd[41]=distcc
install_dir[41]=/home/distcc

ip[42]=10.6.222.128
port[42]=13632
ssh_port[42]=36000
user[42]=distcc
passwd[42]=distcc
install_dir[42]=/home/distcc

