cc_library(
    name = 'zookeeper_sdk',
    srcs = [
        'zk_message.cpp',
        'zookeeper.cpp',
    ],
    deps = [
        '//thirdparty/zookeeper-3.3.3/src/c:zookeeper_generated',
        '//thirdparty/glog:glog'
    ]
)
