java_jar(
    name = 'log4j',
    prebuilt = True
)

java_jar(
    name = 'netty',
    prebuilt = True
)

java_jar(
    name = 'protobuf-java',
    prebuilt = True
)

java_jar(
    name = 'snappy-java',
    prebuilt = True
)

java_jar(
    name = 'zookeeper',
    prebuilt = True
)

java_jar(
    name = 'junit',
    prebuilt = True
)
