cc_binary(
    name = 'zk_conn_test',
    srcs = 'zk_conn_test.cpp',
    deps = [
        '//common/system/concurrency:concurrency',
        '//thirdparty/glog:glog',
        '//thirdparty/zookeeper:zookeeper_mt'
    ]
)

cc_binary(
    name = 'zk_io_test',
    srcs = 'zk_io_test.cpp',
    deps = [
        '//common/base/string:string',
        '//common/system/concurrency:concurrency',
        '//common/system/net:ip_address',
        '//thirdparty/glog:glog',
        '//thirdparty/zookeeper:zookeeper_mt'
    ]
)

cc_binary(
    name = 'zk_node_prepare',
    srcs = 'zk_node_prepare.cpp',
    deps = [
        '//common/system/concurrency:concurrency',
        '//thirdparty/glog:glog',
        '//thirdparty/zookeeper:zookeeper_mt'
    ]
)

cc_binary(
    name = 'zk_node_tree',
    srcs = 'zk_node_tree.cpp',
    deps = [
        '//common/system/concurrency:concurrency',
        '//thirdparty/glog:glog',
        '//thirdparty/zookeeper:zookeeper_mt'
    ]
)

cc_binary(
    name = 'zk_create_ephem',
    srcs = 'zk_create_ephem.cpp',
    deps = [
        '//common/system/concurrency:concurrency',
        '//thirdparty/glog:glog',
        '//thirdparty/zookeeper:zookeeper_mt'
    ]
)

cc_binary(
    name = 'zk_watcher_test',
    srcs = 'zk_watcher_test.cpp',
    deps = [
        '//common/system/concurrency:concurrency',
        '//thirdparty/glog:glog',
        '//thirdparty/zookeeper:zookeeper_mt'
    ]
)

cc_binary(
    name = 'random_watcher_test',
    srcs = 'random_watcher_test.cpp',
    deps = [
        '//common/system/concurrency:concurrency',
        '//thirdparty/glog:glog',
        '//thirdparty/zookeeper:zookeeper_mt'
    ]
)
