#!/bin/bash

PRECOMMIT_DIR=$(cd $(dirname $0) && pwd)
cd $PRECOMIT_DIR

echo -n "Installing presubmit scripts ..." >&2

mkdir -p ~/bin
ln -sf "$PRECOMMIT_DIR"/{presubmit.py,presubmit.sh,work_by_ip.sh,remote_exec.exp} ~/bin
echo ", Done." >&2

echo "All successful." >&2
