#!/bin/bash

command_line="java -classpath .:poppy_java_client.jar:poppy_java_client_test.jar:../../../poppy/java/lib/junit-4.9b3.jar:../../../poppy/java/lib/log4j-1.2.15.jar:../../../poppy/java/lib/netty-3.2.4.Final.jar:../../../poppy/java/lib/protobuf-java-2.3.0.jar:../../../poppy/java/lib/snappy-java-1.0.3.jar:../../../poppy/java/lib/zookeeper-3.3.3.jar com.soso.rpc_examples.AsyncClient "

server_address="127.0.0.1:50000"

if [ "$#" -ge 1 ]; then
    server_address="$1"
fi

request_num="10000"
if [ "$#" -ge 2 ]; then
    request_num="$2"
fi

command_line="$command_line $server_address $request_num"

eval $command_line
